### PR TITLE
Add ability to retrieve map of definitions without requiring a specif…

### PR DESCRIPTION
**Pull request by TristonPlummer**
## What has been done?
Added function to allow developers to grab definition maps rather than map elements

Usage:
```kotlin
val defs = world.definitions.get(ItemDef::class.java)
defs.filter { it.name == "Abyssal whip" }.forEach { println(it.id) }
```

### CODE REVIEW

**Comment by TristonPlummer** [comment]
Probably actually wiser to just have this return an immutable set, as the definitions should contain the id anyway.

**Comment by TristonPlummer** [comment]
I feel that should be the responsibility of the plugin authors, rather than something enforced by the system itself. I'm of the opinion that the plugin system should offer as much power and flexibility as possible, and it's up to the plugin developers to put that to good use.

**Comment by Tomm0017** [comment]
It's hard for me to come up with a real-world example of this feature's usage. The original suggestion on adding this was flawed in the first place as it the attempt was to bind fishing spots via their options, however there's instances where fishing spots can have the same option but contain different fishes

**Comment by TristonPlummer** [comment]
That's fair, at the time of writing this I felt like it was a necessity, though most things can actually be done without requiring this. If it becomes a necessity, I'll open an issue and explain my use case.

**Pull request closed without merging**
