### PR TITLE
Bank tabs with proper insertion

### PR DESCRIPTION
**Pull request by bmyte**
## What has been done?
Implemented the tab functionality of the [Bank] interface to include the tabs list at the top, as well as the empty space components of each tab's last row. Additionally, modifications to the insertion mode were made to account for tab of the already implemented 

## Proposed Changes
  - Added BankTabs.kt object which provides utility functions for dropping [Items] into tabs
  - Added bank_tabs.plugin.kts for handling the unregistered `on_component_to_component_item_swap`
  - Removed erroneous references in Bank.kt to tabs and varbits
  - Modified bank.plugin.kts `on_component_to_component_item_swap` for the [Bank.BANK_MAINTAB_COMPONENT] item to item drops in order to accommodate the tabs list component functionality, as well as the insertion mode portions to support tabs and updating varbits accordingly

### CODE REVIEW

**Comment by bmyte** [comment]
Added support for depositing and withdrawing from tabs in commit [4dfd69f](https://github.com/Tomm0017/rsmod/pull/172/commits/4dfd69f2dd3715464b8b056ac5488a8d0784d1e9)

**Comment by superbmyte** [comment]
Added swapping and inserting tab order in commit [e4ad064](https://github.com/Tomm0017/rsmod/pull/172/commits/e4ad0649449839e9fe5537c6a59f2d3998d68316)

**Comment by bmyte** [comment]
Added swapping and inserting tab order in commit [e4ad064](https://github.com/Tomm0017/rsmod/pull/172/commits/e4ad0649449839e9fe5537c6a59f2d3998d68316)

**Comment by wmcgough** [comment]
This is a good base, but has tons of bugs. Also cannot collapse tabs. 
Thanks for saving me some time though!

**Comment by BenDol** [comment]
@wmcgough will you submit the bug fixes?

**Pull request closed without merging**
